### ISSUE TITLE
mapfix: fixes flow and light issues

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#110]
Is this something that is fixed upstream? It seems unlikely to be fixed in minetest.net version, because the minetest-mods repo has taken in this mod to maintain.
https://github.com/minetest-mods/mapfix

**Comment by slopsbucket** [comment]
Not sure what you're referring to here.

Mapfix is included in Bucket Game, and it works.

There's a much more efficient tool for large areas though. :)
Use coderedit to mark the entire region then use the Replace feature to replace "air" with "air".
