### ISSUE TITLE
Add baked clay (Ethereal NG integrates with it, mobs redo, and farming redo)

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#113]
* Is this in Bucket_Game?
* does codermobs and farming make use of it fully like mobs redo and farming redo do?

**Comment by slopsbucket** [comment]
It is in bucket game. I'm not sure about the integration with other mods, not something I've ever played with.

**Comment by poikilos** [comment]
Solved! Thanks @OldCoder and @slopsbucket
