### ISSUE TITLE
Add round trunks option

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#120]
https://github.com/minetest-mods/round_trunks

**Comment by poikilos** [comment]
Already in Bucket_Game?

**Comment by slopsbucket** [comment]
It creates a horrific amount of black shadows in forests, for some reason the leaves don't get shadows, just the trunks.

**Comment by poikilos** [comment]
bucket_game has it now, and OldCoder fixed the tree shadow issue (with L-systems in general) a while back.

**Comment by poikilos** [comment]
The round trunks are now present for `default:tree`, and optional as of 220114 via `square_trees = true`.
