### ISSUE TITLE
Regular doors and chests are not protected via protection block/symbol

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#141]
If disallowed people can use the door, maybe that's fine. If they can break it, that's bad. Confirmation is needed.

**Comment by slopsbucket** [comment]
Answered in issue #143, done deliberately.

**Comment by poikilos** [comment]
Understood (see my comment there)

**Comment by poikilos** [comment]
There is some work toward protection of additional doors in a MeseLite update. I'm not sure if it applies to Bucket_Game.
