### ISSUE TITLE
Make sure lava is generated (magma crystals are)

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#157]
- Lava seems rare on poikilos.dyndns.org (using seed "BirdLand")
- No lava has been found yet (confirmation needed)

**Comment by slopsbucket** [comment]
Parameters in mapgen were changed last year, lava now has a max_height of -256.

**Comment by poikilos** [comment]
Add to web app getting started guide

**Comment by poikilos** [comment]
> Parameters in mapgen were changed last year, lava now has a max_height of -256.

@HenryNautilus, you must go deeper to find lava.

**Comment by HenryNautilus** [comment]
ah ok thanks
