### ISSUE TITLE
Fine-grained permissions (build vs interact)

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#17]
make compatible with Bucket_Game areas and/or [privilegeareas](https://github.com/minetest-mods/privilegeareas)

**Comment by slopsbucket** [comment]
It was for this reason that OldCoder split privileges. In Bucket Game people with the "interact" privilege can open doors, harvest plants and use machines such as furnaces and grinders, they can also access unlocked chests. But they can't dig or place nodes. They need the "build" privilege for that.

This allows the creation of public facilities such as those in Wonderworld. People can use them but they can't damage them.

**Comment by poikilos** [comment]
> It was for this reason that OldCoder split privileges. In Bucket Game people with the "interact" privilege can open doors, harvest plants and use machines such as furnaces and grinders, they can also access unlocked chests. But they can't dig or place nodes. They need the "build" privilege for that.
> 
> This allows the creation of public facilities such as those in Wonderworld. People can use them but they can't damage them.

Excellent. That resolves the wontfix issue at <https://github.com/minetest/minetest/issues/7057>!

**Comment by poikilos** [comment]
Some stopgap measures:
* default:cloud is fully opaque and unbreakable (confirmation needed)
* <https://github.com/minetest-mods/maptools>: "Adds various special versions of normal blocks, tools, and other map maintainer tools."

**Comment by poikilos** [comment]
To split the issue, I'll move the group-related ideas to #335
