### ISSUE TITLE
Improve Giant Panda Texture - Real Ones Have Large Black Stripe/Band

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#191]

**Comment by slopsbucket** [comment]
The Panda in the LoS game is better looking and has better animations.

**Comment by Poikilos** [comment]
I added this as a PR in minetest-mobs-mods/dmobs.
- https://github.com/poikilos/dmobs/raw/improve-panda-texture/textures/dmobs_panda.png
- https://github.com/poikilos/dmobs/raw/improve-panda-texture/textures/dmobs_panda.xcf

I didn't find a panda in Legends of Survival (LoS) game: https://github.com/ThomasMonroe314/LegendsOfSurvival

**Comment by poikilos** [comment]
This is resolved in the unreleased Bucket_Game 2021-06-25
[codermobs-panda-patch-210330-vs-200527.license-fixed-patch-2021-06-26.diff.txt](https://github.com/poikilos/EnlivenMinetest/files/6720193/codermobs-panda-patch-210330-vs-200527.license-fixed-patch-2021-06-26.diff.txt)
