### ISSUE TITLE
Mossy everything (stone related)?!

### ISSUE THREAD

**Issue by HenryNautilus** [poikilos/EnlivenMinetest#200]
![screenshot_20190323_210534](https://user-images.githubusercontent.com/48847670/54873615-f4038e00-4daf-11e9-8cdd-85a23eb6cd01.png)
I understood the mossy cobble. But turning the bricks into mossy bricks is a little much. I like the idea but it frustrates how I wanted the "untouched by time" look. Maybe making the mossy stone bricks and mossy stone optional/configurable might be one easy fix. Another would be to just lessen the intensity of the texture. It looks ok in water but the moment they're in air. It screams GREEN.
![screenshot_20190323_203537](https://user-images.githubusercontent.com/48847670/54873652-06ca9280-4db1-11e9-8449-4542dc77e03c.png)
Also, what is the system that determines what blocks turn mossy? I look at some underwater cliffs and they're fine. It's mostly just stuff localized at my underwater base.

**Comment by poikilos** [comment]
* This didn't seem to happen until update 190323 (only happened with cobble before)
* suggestion: make configurable for server owners

**Comment by slopsbucket** [comment]
I agree with HenryNautilus here. 100%

There was nothing wrong with the old mossy cobble, it also looked good as a building material in the right places, that new mod is quite unpleasant.

**Comment by Poikilos** [comment]
It turns out this is a Glooptest issue.
