### ISSUE TITLE
Lapis columns are missing

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#220]
* coderbuild/lapis is already based on Napiophelios/lapis so the following can be done:
add `dofile(minetest.get_modpath("lapis").."/columns.lua")` to beginning of `mods/coderbuild/lapis/init.lua`. The line is commented by default, but should probably be configurable instead.

**Comment by slopsbucket** [comment]
I'm looking forward to this.

OldCoder is an old school keyboard man and has a mild phobia of the GUI. :)
