### ISSUE TITLE
carts (minecarts) cannot travel along certain rails

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#255]
Carts cannot travel along certain rails. I think I noticed this issue about a year or more ago in Minetest.net git releases. It may even go back to when they integrated boost carts into minetest_game (https://github.com/minetest/minetest_game/issues/1311), but the issue may not exist in boost_carts--I don't remember.

**Comment by poikilos** [comment]
confirmed in Bucket_Game 2019-05-12

**Comment by slopsbucket** [comment]
It's only default:rail, all the others are fine.

**Comment by poikilos** [comment]
@HenryNautilus I implemented fixes suggested by slopsbucket and OldCoder in my server (some old pre-boost_cart code removed by <https://github.com/minetest/minetest_game/pull/1318> was still present). Test again if possible.

**Comment by poikilos** [comment]
Fixed in Bucket_Game!
