### ISSUE TITLE
lott spider makes loud moaning noise when strikes you

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#263]
lott spider keeps making zombie-like moaning noise each time it strikes

**Comment by poikilos** [comment]
split from issue #248

**Comment by poikilos** [comment]
my improved sounds have been merged upstream, but I want to add more treble using a better recording I made (also of a cucumber, but this time with a studio mic)

**Comment by Poikilos** [comment]
My improved sounds have been merged upstream, but I want to add more treble using a better recording I made (also of a cucumber, but this time with a studio mic).
See:
```Lua
    sounds = {
        war_cry = "*mobs_eerie"                    ,
        damage  = "*mobs_damage_giant_exoskeleton" ,
        death   = "*mobs_death_giant_bug"          ,
        attack  = "*mobs_use_giant_exoskeleton"    ,
    },
```
where *mobs is mobs mod name
Note: `*mobs_eerie` sound was already good in original mob.

**Comment by poikilos** [comment]
Ill revisit the minor sound quality issue in a later commit.
