### ISSUE TITLE
Player's Facing Angle Isn't Used For Placing Rails

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#279]
- [ ] create mesh rails

**Comment by poikilos** [comment]
`raillike` doesn't use facedir apparently (See email 6/7/19 1:17 AM ET from me)

**Comment by Poikilos** [comment]
Raillike doesn't use facedir. This enhancement would have to be done in a mod that uses mesh nodes. See old repo *-branches/turing_carts--add for WIP models (tracked on issue #424 )
