### ISSUE TITLE
WorldEdit forces lava flows to remain

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#29]
lava flows remain after lava source is removed (punching them makes them flow and then vanish)

**Comment by slopsbucket** [comment]
Flowing water as well. Mapfix also makes them start dropping properly.

**Comment by poikilos** [comment]
I am not entirely certain if by "dropping" you mean despawning when source is removed--is this is fixed in mapfix?

**Comment by slopsbucket** [comment]
Can be fixed "by" mapfix. There's no bug, it's just that lava_source and lava_flowing are two different node types.
