### ISSUE TITLE
Neutral Mobs Despawn Frequently (Farming Doesn't Work)

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#3]
Also, certain mob (cow?) in minetest_game despawned even if protected (Mob Protection Rune is expensive anyway, so shouldn't be needed for farming). That can't be tested until main issue is resolved.

**Comment by slopsbucket** [comment]
I wondered about this, it seems to be an added feature and one that I don't like.

**Comment by poikilos** [comment]
TODO: see if this is configurable, or look for responsible code.

**Comment by poikilos** [comment]
NOTE: In mobs redo, one of the animals despawns even with a Mob Protection Rune (may not apply here if mobs were added to Bucket_Game uniformly with new code)

**Comment by poikilos** [comment]
Default should be changed
```
   'remove_far_mobs'        if true then untamed mobs that are outside players
                             visual range will be removed (default is true)
```
Why change: players dont' want to breed animals just to have them die. Forcing players to tame every single juvenile animal to prevent them from disappearing is counter-intuitive.

**Comment by slopsbucket** [comment]
I don't like the despawning at all and I removed that entire section of code in my copy.

Besides, you don't tame animals that you're going to kill, chop up and stack in the freezer. It's in the codermobs/mobs/api.lua file, my copy attached.

The anti drowning code that allows them to walk on water is in there too.
[api.lua.zip](https://github.com/poikilos/EnlivenMinetest/files/3087023/api.lua.zip)

**Comment by poikilos** [comment]
Thanks! I have one issue. What version of Final Minetest is this based on? I'm having trouble making a good patch file due to spacing and variable name differences. You may want to diff against the upstream version such as using meld to make sure you have the latest improvements. I tried a version from before OldCoder added the 1.5 years of upstream changes but still there are differences beyond spawning.

[Bucket_Game-20190416-api.lua-vs-190___.zip](https://github.com/poikilos/EnlivenMinetest/files/3087271/Bucket_Game-20190416-api.lua-vs-190___.zip)

**Comment by slopsbucket** [comment]
This is from 190411.

Just scroll to about 3/4 of the way down the page until you can see the section of code I commented out. The anti-drowning section is a little above that.

Cheers,

Andrew.

**Comment by poikilos** [comment]
Got it, thanks!
[Bucket_Game-20190416-api.lua-vs-190411.zip](https://github.com/poikilos/EnlivenMinetest/files/3087495/Bucket_Game-20190416-api.lua-vs-190411.zip)

**Comment by poikilos** [comment]
Resolved in Final Minetest 190420: "You can make mobs immortal by setting "lifetimer" to 20000 or greater."
