### ISSUE TITLE
"join game" server list sorting

### ISSUE THREAD

**Issue by rtalk101** [poikilos/EnlivenMinetest#332]
"Join Game" menu:

**Part A: Favorite servers auto-sort to the top, but unable to sort servers by number of players**

**Part B: Unable to distinguish "family-friendly" servers from "adults-only" servers**

**Part C: "Num Lock" setting is not respected when searching for a server**

Test C.1: Press upper-row "1234" in search field
Result C.1: "1234" appears in search field

Test C.2: num-lock **OFF**: Press numpad "1234" in search field 
Result C.2: **correctly** "1" and "3" do nothing, "2" and "4" function as "down arror" and "left arrow"

Test C.3: num-lock **ON**: Press numpad "1234" in search field
Result C.3: **INcorrectly** "1" and "3" do nothing, "2" and "4" function as "down arror" and "left arrow"

**Comment by poikilos** [comment]
The list is not curated--the technology of Robert's list is designed to prevent top-down management, so this feature is not possible now. Some sort of rating system may be possible with another layer such as FinalLobby (a WIP project of mine), sorry.
