### ISSUE TITLE
main menu controls tutorial incomplete

### ISSUE THREAD

**Issue by rtalk101** [poikilos/EnlivenMinetest#333]
Inside a minetest server game a player can press ESC to get a menu.
This menu has a "Controls:" tutorial on the right-hand side.

Related to the following issues also about tutorials/onboarding:
#148 tutor: Consider adding tutorial mod (toggle on/off with config, default off)

**Part A: This tutorial is missing instructions for the following important keys for new players:**
H - noclip mode
J - fast mode
K - fly mode
L - pitch fly mode
F10 - console
F12 - screenshot
/spawn - get unstuck

**Part B: Perhaps in a separate section, this tutorial is missing more advanced keys and commands, such as:**
R - unlimited viewing range
F1 - hud display
F2 - chat display
F3 - fog display
/tp \<player\> teleport to player

**Comment by Poikilos** [comment]
This is not really feasible since the list of things could go on forever. The tutorial mod (or forking the tutorial mod) would be a better place for this, so this is not planned, sorry.
