### ISSUE TITLE
Jungle grass is missing by default, but it is necessary for gameplay

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#391]
> The switch to disable Jungle Grass was added in the 190929 release of Bucket_Game, it does not exist in the 190620 version.
> 
> In the versions 190929 and later maps are generated by default with no Jungle Grass, which is needed for gameplay.
-@Slopsbucket on <https://github.com/poikilos/EnlivenMinetest/issues/387#issuecomment-619276005>

Test:
Seed 13165969100545089248 has a jungle at 0,0,0. Fly upward with noclip to see the jungle. In amhi_game, there is jungle grass around you in the jungle, but in Bucket_Game there is not (tested in Bucket_Game 200502).

**Comment by poikilos** [comment]
Here are some seeds along with wich biome they produce at 0,0,0 (the game converts the alphanumeric seeds you enter in the GUI into large numbers):
- aaa: grasslands
- ab: tundra (?) (permafrost_with_stones)
- abc: *_ocean (not surewhich subtype)
- ba: deciduous_forest (?) (various non-coniferous trees from default)
- bb: rainforest_swamp (?) (with rainforest nearby)
- bbb: *_ocean (not surewhich subtype)
- bc: desert
- ca: desert
- cb: rainforest_ocean (?) (with rainforests nearby on two sides)
- cc: *_ocean (not surewhich subtype)

**Comment by slopsbucket** [comment]
Remember a while back when there was an issue with trees and grasses being placed all over the map regardless of biome restrictions? Well back then someone noticed part of the problem - jungle grass everywhere, and the quick fix was to disable jungle grass by default.

I whinged and got the main issue fixed but jungle grass is still disabled by default.

Cheers,
Andrew.

**Comment by poikilos** [comment]
The correct grasses spawn in the correct areas now, and the issue of missing grass by default is fixed in bucket_game 190406 or earlier.
