### ISSUE TITLE
Make all dyes look the same instead of some being bowls instead of piles.

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#486]
- [x] (fixed in Bucket_Game 211107c) bowls produce the incorrect color of bathroom tiles (other dyes (ones that look like piles) produce the correct color of bathroom tiles).

All dyes should look the same instead of some being bowls:
- [x] The bowls are in codorcore/dye/textures but aren't all used:
```
dye_black.png
dye_blue.png
dye_brown.png
dye_cyan.png
dye_dark_green.png
dye_dark_grey.png
dye_green.png
dye_grey.png
dye_magenta.png
dye_orange.png
dye_pink.png
dye_red.png
dye_violet.png
dye_white.png
dye_yellow.png
```

Unifieddyes defines some dye(s) (or can) using its own gray graphic and tinting it: 
- [x] unifieddyes/textures/unifieddyes_dye.png: If I replace it with the new dye texture I drew (along with changing the colorize value from 200 to 128 to look less over-saturated/fake), you can see that unifieddyes replaces blue, cyan, dark green, dark grey, green, grey, magenta, orange, red, violet, and yellow (not black, brown, pink, nor white)--see screenshot:

![screenshot_20220203_100043](https://user-images.githubusercontent.com/7557867/152651944-2094b4b2-410e-459c-806b-1a49ae6d7c07.png)

:edit:
There is now a patch for this.

To apply, set BUCKET_GAME then:
```
cd EnlivenMinetest && git pull && rsync -rtv Bucket_Game-branches/dye-redrawn-vs-220114/ $BUCKET_GAME
```

**Comment by slopsbucket** [comment]
I would like to see this too, The bowls were part of a texture set that Drummyfish was working on but he dropped out of touch before they were complete. Some of the default metal ingot textures are also his.

**Comment by poikilos** [comment]
bucket_game snapshot 220501 or earlier has this patch.
