### ISSUE TITLE
Already-spawned trex will have the wrong texture, as will others where was ever spawned with blank parts due to multiple meshes in model.

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#527]
Note that untextured_mob_body_parts_workaround-vs-211114a mitigates the issue, as already-spawned trex will have the wrong texture since the texture is saved in the world rather than the mobdef
- The texture is saved in the entity in the world db so a brown horse stays brown, which players expect, but maybe there is a way to reset the texture if invalid. Invalid could mean: missing texture; different number of material ids assigned than is in the mobdef.

**Comment by Poikilos** [comment]
Only temporary (caused by loading old world after renaming mobs in mod) and solving it would be complex, so it doesn't seem to be worth it.

**Comment by poikilos** [comment]
Try the following workaround:  `/giveme mobs:mob_reset_stick ` then hit mob with it.
