### ISSUE TITLE
Fedora 38 has trouble compiling 5.x

### ISSUE THREAD

**Issue by Poikilos** [Poikilos/EnlivenMinetest#600]
I compiled with

perl mtcompile-program.pl --trolltest --client build

using

Fedora 38

The CXX compiler identification is GNU 13.1.1

Further details can be seen in the attached log.

Fedora dependencies installed (worked a few years ago for Final Mintest) are shown in the "elif [ ! -z "$this_dnf" ]; then" clause of the if statement in my cross-distro dependency script: https://raw.githubusercontent.com/Poikilos/EnlivenMinetest/master/install-minetest-build-deps.sh

emailed to @OldCoder Aug 4, 2023

Attachment:
[EN 600 compile log --trolltest.log](https://github.com/Poikilos/EnlivenMinetest/files/12265074/EN.600.compile.log.--trolltest.log)

**Comment by mckaygerhard** [comment]
i guess gcc 13 its more strict and that's all. with `error: ‘shared_ptr’ in namespace ‘std’ does not name a template type`

**Comment by Poikilos** [comment]
OldCoder has fixed it somehow. Also note that `include <memory.h>` was missing from  src/clientiface.h in 5.3.0-dev-806862e74-dirty and he fixed that as well. Newer versions may be too destructive to the world and protocol to even be useful. Every minor revision is a rugpull, hence "trolltest".
