### ISSUE TITLE
Running trolltest without shell such as via run-any in VSCode causes error

### ISSUE THREAD

**Issue by Poikilos** [Poikilos/EnlivenMinetest#616]
"error while loading shared libraries: cannot open shared object file: No such file or directory"
- Only occurs when running trolltest from visual studio to view Lua tracebacks using run-any (paths in Lua tracebacks can be restored with outputinstector)

**Comment by Poikilos** [comment]
It turns out it is fixed after restarting Visual Studio, so probably fixed by 6cdf41e.

**Comment by Poikilos** [comment]
It seems that installing lsb fixed it, but that is probably a coincidence and the package or one of its dependencies ran `ldconfig` as root. I will revert the arch-specific changes as now it works without `LD_LIBRARY_PATH`.
- New recommended fix is: `sudo ldconfig` (If you find a different fix, please post it here).
- The included VSCode `code-workspace` files can be loaded in VSCode for Linux and automatically use `run-any`. The `code-workspace` file(s) must be modified to suit your minetest location (Only run-in-place is tested, but this whole thing is for testing anyway so hopefully that is not an inconvenience).
- Note that if outputinspector is cloned to same parent directory, it will transform truncated Lua tracebacks from `` to `` so you can click the error to visit the line of Lua which is the point of `run-any`.

**Comment by mckaygerhard** [comment]
i will try to find a fix, by now this case is only for developers, so it dont affect users.. i will focus this weekend in test final minetst from point of view of a gamer.. 

but **important note: `LD_CONFIG_PATH` WILL EXIST ALWAYS IN ANY LINUX**, if you dont have it, is cos you are runnin a M$ promotiion tool (vscode), ldconfig only helpt environment to **preload new paths for the linker**, and finally, sudo is deprecated in amny linuxes due security issues, by example alpine linux

**Comment by Poikilos** [comment]
You keep commenting on the old code I already said I fixed. I responded on the old commit which was reverted:

> @mckaygerhard Please see commits listed under issue #616 including the later commit which reverts this commit. `sudo ldconfig` and reverting this commit and restarting VSCode seems to have fixed everything. The problem probably only occurs after a system update affecting libraries used by Minetest and before `sudo ldconfig` in a shell that was running before the system update, it seems. There is no need to manually add the directories anymore.

**Comment by mckaygerhard** [comment]
**dont worry this dont affect end users and yeah noted. ..** 

i just explain that is not 100% a fix **cos ldconfig just updated paths (that in your case solve the issues)** we must wait other user to test that! cos i dont use vscode
