### ISSUE TITLE
Set Spawn Using Bed (setspawn is not a Command, Bed is Better for Immersion)

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#74]
Beds have not been tested yet on my end. Someone on my server should confirm whether Bucket_Game already implements this. https://poikilos.dyndns.org
Currently, players go back to a certain place after death. The way this place is determined is not known. My server doesn't have a spawn set, so players spawn at or close to 0,2.5,0 --but for some reason, still are revived at a different location determined by unknown means. This location is their "spawn point" from then on. How is it determined?

**Comment by slopsbucket** [comment]
I haven't tested, but I've seen the commits for bed spawning, if you die you should return there.

Also not tested, sometimes I have to travel a long way in search of resources, if this is the case I take a bed with me so I can skip night time and avoid monsters. I would guess that a respawn location stays set even if the bed is removed afterwards.

I also don't know if "home" points make valid respawn points.

**Comment by poikilos** [comment]
OldCoder added Bucket_Game/mods/codercore/fallback_spawn which should help server owners manage spawn more easily.

**Comment by poikilos** [comment]
* This was already done in Bucket_Game--the weird place players respawned was the following world.conf setting: `static_spawn_point          = 0, 2.5, 0`
* Setting static_spawn_point implies `disable_multispawn = true`
* See also <https://minetest.org/changes.html> for version 190225 and later changes for 190323 (2019-03-23):

> * To see spawn points: /listspawn or /listspawns
>         * To TP to a random spawn point: /spawn
>         * To TP to a specific spawn point: /spawn 3
>         * To add one: /addspawn 20, 10, 30 or /addspawn 20 10 30
>         * To delete one: /delspawn 3 or /deletespawn 3
