### ISSUE TITLE
Supply Converter Always Draws Power

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#89]
(HV to MV to LV converter)

**Comment by slopsbucket** [comment]
More of a limitation than a bug?

Use power stations in Bucket City as examples, underneath the Club House near the eastern end of the city.

The power converters not only constantly draw 10,000 eu, they constantly put out 9000 eu. They are restricted to that no matter how much power you supply them.

This means you have to put a little planning into the design of your power plant to get the best value for your resources. If playing properly they're quite expensive to build.

So is it a bug or is it a feature that promotes thought and planning?

**Comment by poikilos** [comment]
As I recall, certain real life power supplies (ones not marked "rated for...") always draw a certain amount of power, so I agree with your assessment.
