### ISSUE TITLE
Fix Jump Mechanics, Possibly Allow Disabling Sneak Glitch

### ISSUE THREAD

**Issue by poikilos** [poikilos/EnlivenMinetest#96]
I understand the sneak glitch was re-added for glitch elevators in legacy worlds. Can this be disabled in Bucket_Game? This may be related to #66

**Comment by poikilos** [comment]
See if no_sneak_glitch [disables fast glitch-climbing up certain patterns] https://forum.minetest.net/viewtopic.php?f=11&t=10424 is compatible with Bucket_Game

**Comment by slopsbucket** [comment]
Yes, it can be disabled:

disable_classic_sneak = true

**Comment by poikilos** [comment]
TODO: change setting on Center of the Sun server then close
